messaging:
  image: rabbitmq:3
  ports:
   - "5672:5672"
   - "15672:15672"
db:
  image: mongo:latest
  ports:
   - "27017:27017"
autho:
  image: httpprincess/authorizator:latest
  ports:
   - "5000:5000"
updater:
  image: httpprincess/store-updater:latest
#  image: updater2
  links:
    - db
    - messaging
worker1:
  image: benedicere/metahosting-dummyworker
  links:
    - db
    - messaging
  environment:
    - DB_LOCAL_COLLECTION=dummy1-local-instances
    - WORKER_NAME=dummy1
    - WORKER_DESCRIPTION=dummyworker 1
worker2:
  image: benedicere/metahosting-dummyworker
  links:
    - db
    - messaging
  environment:
    - DB_LOCAL_COLLECTION=dummy2-local-instances
    - WORKER_NAME=dummy2
    - WORKER_DESCRIPTION=dummyworker 2
facade:
   build: .
   command: /app/run.py
   ports:
    - "8080:8080"
   links:
    - db
    - autho
    - messaging
